Add reviews
vladbakumenko/java-filmorate pull request #10
Opened 2022-11-22 11:29 UTC by Anton-Phedorenko

Привет,ребята! Сделал отзывы,жду вашей критики)

2022-11-22 12:31 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +@Component
@Component аннотацию можно убрать, т.к. есть @RestController

2022-11-22 12:32 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public ReviewController(ReviewService reviewService) {
Конструктор не нужен, если добавить @RequiredArgsConstructor

2022-11-22 12:32 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +
пустую строку можно убрать

2022-11-22 12:35 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new RuntimeException("Описание фильма превышает максимальное количество знаков 200");
а зачем было менять класс ошибки? вроде всё в порядке было)

2022-11-22 12:35 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @Override
toString можно убрать, он в Data включается насколько помню)

2022-11-22 12:36 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public String toString() {
вроде как @Data аннотация сама добавляет toString из коробки

2022-11-22 12:40 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +        Integer id = keyHolder.getKey().intValue();
тут можно использовать примитив

2022-11-22 12:41 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +        return jdbcTemplate.queryForObject(sql,
а ты не думал тоже маппер сделать, как DirectorMapper, чтобы не использовать makeReview?

2022-11-22 12:45 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersDao.java
>      }
пишу тут, т.к. sprint.json больно большой. Зачем в проете нужны тесты постмана? они для разных веток все равно разные. А вот инттеграционных тестов стоило бы добавить.

2022-11-22 12:51 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void validReview(Review review) {
а нельзя ли часть проверок на null, empty заменить аннотациями в модели? оставить только те, что проверки логические

2022-11-22 12:51 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void validReview(Review review) {
метод сам можно в validateReview переименовать - стоит от глагола плясать в именовании

2022-11-22 12:53 UTC, pavlovAndrei requested changes

2022-11-22 12:53 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (review.getUserId() < 0||review.getUserId()==null) {
кстати, можно каждый класс комбинацией Alt+Ctrl+L форматировать отсутупы автоматом

2022-11-22 12:59 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersDao.java
> +        String sql = "SELECT * FROM users";
чем так не устроили маленькие буквы?) мне кажется стоит вносить изменения действительно важные, что бы потом конфликтов при мёрже лишних не было, ну это лично моё видение конечно, или за это ревьюер ругался? просто у меня проблем вроде не было)

2022-11-22 12:59 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +        String sql = "INSERT INTO feed(id_entity,id_user,timestamp,event_type,operation) VALUES(?,?,?,?,?)";
не надо было делать функционал под события, так как элементарно поля объекта Feed другого типа, но, уже лучше оставь, я сам переделаю потом под реализацию

2022-11-22 12:59 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Integer filmId;
можно использовать примитивы как мне кажется, проблем быть не должно...

2022-11-23 12:27 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersDao.java
> +        String sql = "SELECT * FROM users";
Это было требование ревьюера)

2022-11-23 12:36 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Integer filmId;
Дело в том,что с примитивами не выходит лично у меня. Вот например надо нам проверить на null: можно привести к Integer,но это некрасиво,а если делать с аннотациями,то spring выбросит какое то свое исключение и будет ошибка 500,а постман к примеру ждал 404. Но если знаешь как это решить, то я поменяю поменять на примитивы)

2022-11-23 14:06 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +@Component
Убрал

2022-11-23 14:07 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            throw new RuntimeException("Описание фильма превышает максимальное количество знаков 200");
Это я просто не понимал почему тесты не проходит и забыл на место вернуть)

2022-11-23 14:07 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    public String toString() {
да,так и есть)

2022-11-23 14:08 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +        Integer id = keyHolder.getKey().intValue();
с примитивами у меня бывают проблемы,я Владу тут написал
https://github.com/vladbakumenko/java-filmorate/pull/10#discussion_r1030390390

2022-11-23 14:08 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/ReviewDao.java
> +        return jdbcTemplate.queryForObject(sql,
сделал

2022-11-23 14:08 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersDao.java
>      }
тест сделал

2022-11-23 14:09 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    public void validReview(Review review) {
некоторые проверки делегировал аннотациям и метод переименовал

2022-11-23 14:14 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    @Override
согласен,убрал)

2022-11-23 15:05 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UsersDao.java
> +        String sql = "SELECT * FROM users";
понял, хорошо)

2022-11-23 15:08 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Review.java
> +    private Integer filmId;
хмм, надо подумать, просто в других моделях везде использованы примитивы, потому я от этого отталкивался, но, видимо там помогает валидация в самих сервисах для классов фильмов и юзеров, может поэтому и нет проблем с возвратом нужных ошибок)

2022-11-23 15:21 UTC, Anton-Phedorenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        } else if (review.getUserId() < 0||review.getUserId()==null) {
Сделал везде форматирование

2022-11-23 15:36 UTC, merged