Develop
vladbakumenko/java-filmorate pull request #25
Opened 2022-11-24 16:18 UTC by vladbakumenko

2022-11-25 17:53 UTC, FanaticFiz requested changes

2022-11-25 17:53 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +package ru.yandex.practicum.filmorate.controller;
Не выполнено требование:

`Обязательно должно быть описание того, какие задачи выполнила группа, в описании пул-реквеста или в файле readme`

2022-11-25 19:01 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +package ru.yandex.practicum.filmorate.controller;
добавил список выполненных задач в файл readme

2022-11-26 18:49 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    public Collection<Director> findAll() {
Используйте более распространенный интерфейс `List` 
Если просто возвращать то разницы нет, но если работать со списком то List куда более узкий и функциональный.

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/resources/data.sql
> +ALTER TABLE directors ALTER COLUMN id RESTART WITH 1;
Ваш сервис крешится при попытке запустить его более одного раза!
Вот лог:

```
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Попытка создания второго первичного ключа
Attempt to define a second primary key; SQL statement:
ALTER TABLE directors ALTER COLUMN id RESTART WITH 1 [90017-214]
```

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getPopularFromDb(count, genreId, year);
Не надо приписывать `FromBd` (или нечто подобное) к названиям методов...

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("director/{directorId}")
В пути маппингов в этом сервисе творится нечто странное и совершенно точно не консистентное...

В одних местах путь содержит слеш `@GetMapping("/{id}")`
В других нет `@PutMapping("{id}/like/{userId}")`

Сделайте единообразно! Везде есть `/` в начале

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    public void addFeed(int idEntity, int idUser, EventType eventType, Operation operation) {
Методы не висят в воздухе!
Поэтому нет нужды в них повторять название сущности, например: `feedService.addFeed()`

Получается масло-масляное! 

Лучше: `feedService.add()` `feedService.getByUserId()`


Но в целом в вашей работе это не часто. В основном методы в сервисах названы хорошо!

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/resources/schema.sql
> +    id_event BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
Что качается БД

Не хватает выравнивания.

```
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR,
    login    VARCHAR,
    name     VARCHAR,
    birthday DATE
);
```

Не видно продуманной работы с полями в БД.
Какие поля можно сделать короче, чтобы сэкономить место на хранение, какие поля нужно поставить `not null` потому что без них записи не имеют смысл?

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
>  public class MPAController {
Тут первым бросается в глаза название класса, не по `Java naming convention`!
`MPA` следует писать `Mpa` даже не смотря на то что это аббревиатура... `Xml`, `Json` и т.д.
`MPAController` -> `MpaController`

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private void validFilm(Film film) {
Есть правило расположения методов в классе. 
Сначала идут все публичные методы потом приватные...

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
В целом есть еще проблема с классами эксепшенов в этой работе.

Первое.
`ValidationException` судя по тому как он используется и обрабатывается в `ErrorHandler`, должен называться `BadRequestException` 

Поскольку у нас веб сервис и ошибки в присланных нам данных мы интерпретируем как "плохой запрос": BadRequest -> BadRequestException

Второе
FilmNotFoundException, ObjectNotFoundException, UserNotFoundException - зачем создано три про одно и тоже? 
Мы замучаемся создавать эксепшены на каждую сущность в большом приложении!
Должен существовать один: `NotFoundException`, а в сообщении вы даёте подробную инфу: какая сущность и почему не найдена!

Третье
Во всех классах ексепшенов навалена куча неиспользуемых конструкторов.
Приберитесь там!

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
>      }
Напишу в случайном месте коммент по классу `ErrorHandler`, поскольку он не попал в dif.

Вообще вижу по этой работе что вы, такое ощущение, совсем не знаете или забыли про существование логера!
А ведь это важно!
И особенно важно логировать когда возникают ошибки.
Поэтому в классе ErrorHandler надо логировать обязательно!

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/MPAService.java
> +@RequiredArgsConstructor
Давайте поговорим теперь о ваших сервисах...
У вас проблема, я называю её: "худые сервисы" - сервисы которые ничего не делают!

А должны!
Именно в них должна быть реализована бизнес логика, именно они являются связующим звеном в нашей трёх-звенной архитектуре приложения. 

вот например метод: `getMpaById` просто транслирует работу в `dao` а тот кидает ексепшн, если не нашел сущность! 
Это не верно! 
dao не должен этого делать, он забрал эту работу у сервиса!

Как должно быть:
Сервис обращается к dao и анализируя ответ от него кидает ексепшн - если этого требует наша бизнес модель.

А посему, конкретно по методам `findById` лучше всего возвращать `Optional` чтобы сервису было удобно с ним работать. Попробуйте!


И это у вас поголовно во всех сервисах. 
Нужно проследить чтобы именно они выполняли работу, а не dao !

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.addFeed(rw.getReviewId(), rw.getUserId(), EventType.REVIEW, Operation.UPDATE);
Статики можно предварительно импортировать и получить более читабельный и удобный код

```
feedService.addFeed(rw.getReviewId(), rw.getUserId(), REVIEW, UPDATE);
```

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final LikesDao likesDao;
Этот класс тоже начинается с приватного метода, что как вы уже знаете не верно.

Но есть еще одна проблема.
В  метод валидации `validUser(User user)` просочилась бизнес логика.

Вот она:

```
if (user.getName() == null || user.getName().isEmpty() || user.getName().isBlank()) {
            log.warn("Попытка создать пользователя с пустым именем, вместо имени будет присвоен логин");
            user.setName(user.getLogin());
        }
```

Это уже не валидация - это именно бизнес логика.

И по поводу названия метода.
Если мы кидаем ексепшены по ходу проверки то метод лучше так и назвать `throwIfUserNotValid`

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorStorage.java
> +    Director getById(Integer id);
Комментариев было много., поэтому повторюсь тут точечно...

В идеале в dao применять глагол `find` а не `get` 
Т.е. `findAll`, `findById` 

И возвращать `Optional`
`Optional<Director> getById(Integer id);`

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/ReviewStorage.java
> +}
Этот класс явно не был причесан - нарушен `code style`

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +    private final RowMapper<Director> directorMapper;
Название `directorMapper` может быть воспринято как маппер моделей, поэтому надо уточнить `directorRowMapper`.

ну и на примере этого dao давайте подсвечу чего не должно быть тут, а должно быть в сервисе...

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +            throw new ObjectNotFoundException(format("Director with id: %d not found in DB", id));
1. Подобные эксепшены кидает сервис

2022-11-26 18:49 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +        getById(director.getId());
2. Этот вызов сделан для того чтобы проверить что пользователь сущность существует - должно было быть сделано в сервисе.

2022-11-27 14:36 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        feedService.addFeed(rw.getReviewId(), rw.getUserId(), EventType.REVIEW, Operation.UPDATE);
поправил.

2022-11-27 14:41 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getPopularFromDb(count, genreId, year);
поправил.

2022-11-27 14:44 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("director/{directorId}")
поправил.

2022-11-27 14:50 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FeedService.java
> +    public void addFeed(int idEntity, int idUser, EventType eventType, Operation operation) {
поправил.

2022-11-27 14:53 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/MPAController.java
>  public class MPAController {
поправил.

2022-11-27 15:01 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private void validFilm(Film film) {
поправил.

2022-11-28 17:48 UTC, vladbakumenko commented on src/main/resources/schema.sql
> +    id_event BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
поправил.

2022-11-28 17:49 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +
поправил.

2022-11-29 23:07 UTC, Anastassvirs approved these changes

2022-12-01 03:52 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Optional<Director> director = directorStorage.findById(id);
`Optional` даёт удобство в написании кода. 
Самое частое что употребляется это метод `orElseThrow`

Вот пример:

```
    public Director getById(Integer id) {
        return directorStorage.findById(id)
                              .orElseThrow(() -> new NotFoundException("Not found director with id: " + id));
    }
```

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +        Review rw = reviewDao.findById(review.getReviewId()).orElseThrow(() -> new NotFoundException("Отзыв не найден"));
Даже если код помещается в одну строку, при использовании цепочки вызовов, лучше выделять каждую осмысленную операцию на новую строку.
Ну пример я уже приводил чуть выше...

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +        String sqlQuery = "DELETE FROM film_directors WHERE director_id = ?";
Обратите внимание. Можно было бы в SQL выстроить каскадирование при удалении сущности director. 
И далее с hibernate тоже не нужно будет удалять связи `film_directors`

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
> +import ru.yandex.practicum.filmorate.exception.BadRequestException;
не забывайте чистить импорты...

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
>          return jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
Вот тут сокрыто то чего надо сильно опасаться... 
Название ему N+1 запрос.

Давайте разберём на этом примере.
Пусть у нас есть 100 фильмов... а у каждого из них есть жанры.
Для того чтобы собрать всё в одно и отдать при запросе нам нужно:

- достать все фильмы
- и все жанры к ним

Если делать "в лоб"(так сделано тут сейчас) то приходиться к каждому из 100-а фильмов отдельным запросом доставать еще и жанры... так сделано в `makeFilm(rs)`

Получается ОДИН запрос на получение всех 100 фильмов и еще 100 запросов чтобы к каждому фильму подтянуть жанры....
Это и называется проблема `N+1`


Чтобы её избежать мы должны придти к всего ДВУМ запросам, вместо 101 !
- первый запрос на все фильмы
- второй на все жанры для этих фильмов

И потом насыщаем фильмы инфой о жанрах.

И всё это проделываем, конечно же, в сервисе!

Вот примерный код:

```
public List<Film> getAll() {
	List<Film> films = super.getAll(); 
	genreStorage.load(films); // достаём все жанры и насыщаем фильмы ими

        return films;
	}
```

2022-12-01 03:52 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikesDao.java
> +        final String sqlQuery = "select * from films f "
Оформляйте SQL запросы. Служебные команды SQL в верхнем регистре!

2022-12-01 07:24 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/LikesDao.java
> +        final String sqlQuery = "select * from films f "
Исправил

2022-12-01 07:24 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
> +import ru.yandex.practicum.filmorate.exception.BadRequestException;
Удалил

2022-12-01 07:25 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +        String sqlQuery = "DELETE FROM film_directors WHERE director_id = ?";
Добавил констрейнт для таблицы

2022-12-01 07:25 UTC, pavlovAndrei commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        Optional<Director> director = directorStorage.findById(id);
Исправил

2022-12-01 09:49 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
>          return jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
@FanaticFiz привет, а подскажи пожалуйста, правильно ли я понял, что ты имеешь в виду что-то подобное:

2022-12-01 09:59 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
>          return jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
@FanaticFiz привет, а подскажи пожалуйста, правильно ли я понял, что ты имеешь в виду что-то подобное:

метод findAllFilms() в FilmDao будет получать список фильмов без присвоения жанров и добавить в GenreDao метод, который будет делать запрос в базу и возвращать например Map<Integer, List<Genre>>, где ключом будет id фильма, а список это список соответствующих жанров фильма, и потом в методе сервиса получив эти два хранилища через цикл присваивать фильмам список жанров? верное понимание? или совсем не в ту степь?

2022-12-01 11:19 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmsDao.java
>          return jdbcTemplate.query(sql, (rs, rowNum) -> makeFilm(rs));
да всё верно!

2022-12-01 18:24 UTC, FanaticFiz approved these changes

2022-12-01 18:24 UTC, FanaticFiz commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Map<Integer, Genre> getMapOfFilmsIdAndGenres() {
Получается таки мы не правильно понял друг друга))
В целом то конечно проблему мы решили, но...

Надо было бы передавать фильмы сюда списком и только для этих фильмов искать жанры, а не для прям всех всех. 
Сейчас это прокатывает поскольку используется именно в методе где нужно как раз для всех. Но гибче было бы принимать список фильмов.

2022-12-01 18:43 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Map<Integer, Genre> getMapOfFilmsIdAndGenres() {
а, хорошо, действительно, сейчас исправлю), но, на самом деле основной тупик у меня был с тем, что я думал, что через метод jdbcTemplate.queryForMap легко получится получить мапу и дальше с ней работать, но поискал примеры реализации и что-то так и не понял, как работать с такой задачей, если требуется именно получать в значениях списки с объектами, например Genre, потом я подумал, что можно тогда не получать жанр в мапе, а записывать туда лист с айдишниками жанров по ключу айди фильма, тоже что-то не получилось, в итоге уже решил сделать через дто, так как больше ничего не придумывалось)

2022-12-01 19:58 UTC, vladbakumenko commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +    public Map<Integer, Genre> getMapOfFilmsIdAndGenres() {
@FanaticFiz внёс изменения)

2022-12-12 09:17 UTC, merged